create table
    public.users (
        id bigint generated by default as identity not null,
        name character varying not null,
        created_at timestamp with time zone null default now(),
        constraint users_pkey primary key (id)
    ) tablespace pg_default;

    